"""Replace created_by with teacher_id in Exercise model

Revision ID: b746bfecc380
Revises: f6a0245858b7
Create Date: 2025-03-07 22:20:38.890143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b746bfecc380'
down_revision = 'f6a0245858b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['teacher_id'], ['id'])
        batch_op.create_foreign_key(None, 'class', ['classroom_id'], ['id'])
        batch_op.drop_column('class_id')

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('exercise_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['teacher_id'], ['id'])
        batch_op.drop_column('solution')
        batch_op.drop_column('level')
        batch_op.drop_column('is_in_library')
        batch_op.drop_column('content')
        batch_op.drop_column('subject')
        batch_op.drop_column('image_path')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('is_in_library', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('solution', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.alter_column('exercise_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'class', ['class_id'], ['id'])
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('classroom_id')
        batch_op.drop_column('updated_at')

    op.create_table('submissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('submitted_at', sa.DATETIME(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('answers', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
