"""Update TextHole model structure

Revision ID: f0126526449e
Revises: 
Create Date: 2025-02-24 18:21:12.784009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0126526449e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_hole', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_before', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('correct_answer', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('text_after', sa.Text(), nullable=True))
        batch_op.drop_column('position')
        batch_op.drop_column('answer')
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_hole', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('answer', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('position', sa.INTEGER(), nullable=False))
        batch_op.drop_column('text_after')
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('text_before')

    # ### end Alembic commands ###
